### ISSUE TITLE
Comparison to Matchbox

### ISSUE THREAD

**Issue by entropylost** [wasm-peers/wasm-peers#1]
https://github.com/johanhelsing/matchbox: "Painless peer-to-peer WebRTC networking for rust wasm"

Also is there any way to use a custom signalling service?

**Comment by tomkarw** [comment]
Hi,
thanks for being the first one to create an issue!

> https://github.com/johanhelsing/matchbox: "Painless peer-to-peer WebRTC networking for rust wasm"

To be honest, I didn't do much research before starting this project.

Yeah, we are trying to accomplish the same thing. I even see gaming mentioned in rationale and some naming conventions, which was also the starting point of this project ("Rust gaming in browser" B.Eng. thesis).

They seem to rely on polling and busy loops, where I opted to rely on underlying callbacks. I'd be curious why they decided on this approach. They seem to have a native implementation as well, which is an awesome feature this project lacks at the moment. Also, for now this library only allows sending string data and not pure bits, but that would be relatively easy to add. Otherwise, the projects are eerily similar :).

I couldn't get their example game to run, so I would count our two nice apps as an advantage.


>  Also is there any way to use a custom signalling service?

If you mean providing a completely different signaling server and structure of messages that this server and library rely on, then no.

The main point of this project is to provide signaling out-of-the-box, and I didn't think there is a need to generalize it over multiple possible implementations. That would certainly complicate the code greatly.

What is a use case for such custom signaling? If you could explain it in greater detail, I could maybe consider it.

**Comment by entropylost** [comment]
Custom signalling is mostly because I'd like to have a single server process rather than multiple, but it wouldn't be that inconveinent to change to using a separate process for signaling.
I do absolutely need to be able to send bits as messages though. If you are adding that, it might make sense for you to have a higher-level api using serde and bincode; although I wouldn't need that, it's likely that others would find it helpful.

**Comment by johanhelsing** [comment]
Hey, matchbox creator here

> They seem to rely on polling and busy loops, where I opted to rely on underlying callbacks. I'd be curious why they decided on this approach.

There should be no busy loops in matchbox, please create an issue if you've found one.

As for how you you poll for messages: I wanted the library to work well with bevy_ggrs and bevy, and in that setup, handling messages once per frame was the most natural approach. Bevy's `App::run` blocks until the game is finished, so I needed a way to process messages while bevy was running, which is why I opted to return an async future that can be awaited by bevy's task pool runner.

Bevy usually processes game logic once per frame in non-blocking, non-async systems, which is why it was convenient that the user-facing receive function itself isn't blocking or async. Maybe other game engines or use-cases have architectures where this is inconvenient. If so, I'd very much like to hear about it!

> I couldn't get their example game to run, so I would count our two nice apps as an advantage.

How so? What happened? A bug report would be very welcome.

I'd also be interested in other ways our projects are different.

From a quick scan of the docs, this what I've found so far:

- wasm-peers has a `/one-to-many` endpoint, which we don't have in matchbox, connections are always full-mesh.
- matchbox provides an api: `/scope?next=3`, which will match the next three players in a full-mesh connection, and then create a separate mesh for the next three players to join. Is there an equivelent in wasm-peers?
- Also, I'm confused as to why wasm-peers has a specific endpoint for one-to-one? couldn't just one of the other endpoints be used for that?

**Comment by tomkarw** [comment]
> There should be no busy loops in matchbox, please create an issue if you've found one.

Sorry, I should've dug deeper into source code before asking specific questions. I didn't imply that there were any busy loops, but rather I was wondering how you wrap the underlying callback.  
If I understand correctly, you put the incoming messages in `UnboundedSender<(PeerId, Packet)>` for further consumption.

> > I couldn't get their example game to run, so I would count our two nice apps as an advantage.
> 
> How so? What happened? A bug report would be very welcome.

I didn't realize you are matched with any other person and was looking for some ID to connect as the second user to the same session myself, that's on me for not reading more thoroughly. When I opened the link twice, I only got `Waiting for 1 more player(s)` in both browsers, now on another attempt, it connected after some delay.

I think allowing for generation of a unique session id that you can share with somebody to get a "private" game would be a nice improvement, even for the demo. From README I see signaling server supports this:
```
wss://match.example.com/awesome_game_v1.1.0_pvp?next=2
```
I can create an issue about it. 

> I'd also be interested in other ways our projects are different.

I think callback-vs-polling is the most meaningful one.

>  matchbox provides an api: `/scope?next=3`, which will match the next three players in a full-mesh connection, and then create a separate mesh for the next three players to join. Is there an equivelent in wasm-peers?

This goes back to what I said about your demo example. In `wasm-peers` demo, you create a `private` session based on the `SessionId` generated. In the case of `one-to-many` and `many-to-many` connections, it has a caveat of not limiting the number of peers that can connect, if all of them know the specific session id.

>  Also, I'm confused as to why wasm-peers has a specific endpoint for one-to-one? couldn't just one of the other endpoints be used for that?

This topology was the starting point of the project. As to why it's in the library API, it has simpler callbacks, as you don't have to deal with identifying different peers. As to why it's a different endpoint in the signaling server, when introducing the next two topologies I wanted to keep the implementations clean and separate (merging them would require introducing some conditionals).

I'm definitely thinking about cleaning up the duplications present in both the library and signaling server.  
I'm curious what you think about keeping `one-to-one`, `one-to-many` and `many-to-many` as different features for the end user.

**Comment by johanhelsing** [comment]
>  When I opened the link twice, I only got Waiting for 1 more player(s) in both browsers, now on another attempt, it connected after some delay.

Perhaps both windows weren't visible and you got hit by browser throttling?

> I think allowing for generation of a unique session id that you can share with somebody to get a "private" game would be a nice improvement, even for the demo.

You can make up your own "secret id in the existing demo: https://helsing.studio/box_game/?room=my_super_secret_room

But I guess better advertising that that's a possible way to use it a is probably a good idea.

> I'm curious what you think about keeping one-to-one, one-to-many and many-to-many as different features for the end user.

I think the one-to-many feature is really cool! It enables client-server architectures to run (almost) entirely in the browser.
